// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY ./script/BuildPointers.sol

/// @title LibCloneFactoryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of the current
/// `CloneFactory` release. Lets consumers verify/deploy against a precommitted
/// address + hash rather than a registry. The frozen per-release record lives
/// in `src/generated/<tag>/CloneFactory.pointers.sol`.
library LibCloneFactoryDeploy {
    address constant CLONE_FACTORY_DEPLOYED_ADDRESS = address(0x444acC29d63fa643E8adCC35FD9aa6DE111dCb39);
    bytes32 constant CLONE_FACTORY_DEPLOYED_CODEHASH =
        0xf21b813c7075a1621285df3a8369d0652c31ea80cb807be1aaadafeecd134475;
}
