name: src-standalone
on: [push]
jobs:
  src-standalone:
    runs-on: ubuntu-latest
    steps:
      - uses: rainlanguage/rainix/.github/actions/nix-cachix-setup@main
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop .#sol-shell -c ./.github/build-src-standalone.sh
